config/routes.rb
Rails.application.routes.draw do
  root "groups#index"
  devise_for :users
  resources :groups, only: [:new, :create, :edit, :update, :index] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: { message: "を入力してください" }
  has_many :users_groups
  has_many :users, through: :users_groups
  has_many :messages
  accepts_nested_attributes_for :users
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :body, presence: true
  mount_uploader :image, ImageUploader

  def create_hash(message)
    data =
     {  name: message.user.name,
        body: message.body,
        user_id: message.user_id,
        created_at: message.created_at,
        image: message.image.url(:thumb),
        updated_at: message.updated_at,
        group_id: message.group_id,
        id: message.id
     }
    return data
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :users_groups
  has_many :groups, through: :users_groups
  has_many :messages
end

app/models/users_group.rb
class UsersGroup < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @group = Group.new
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def index
    @groups = Group.all
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice: "グループが生成されました"
    else
      render new_group_path
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group)
    else
      render action: :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def find_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: :index

  def index
    @message = Message.new
    @group = Group.find(params[:group_id])
    @messages = Message.where(group: params[:group_id])
    array = Array.new
    @messages.each do |message|
      mes = message.create_hash(message)
      array << mes
    end
    respond_to do |format|
      format.html {}
      format.json { render json: array }
    end
    # binding.pry
  end

  def create
    @message = Message.new(create_params)
    respond_to do |format|
      if @message.save
        format.html
        format.json {
          render json: @message.create_hash(@message)
        }
      else
        format.json { redirect_to root_path, alert: "メッセージを入力してください。" }
      end
    end
  end

  private
  def create_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id, group_id: params[:group_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/common/_error.html.haml
- if error.any?
  #error_explanation
    %h2
      = @group.errors.count
      error prohibited this chat_group from being saved:
    %ol
      - @group.errors.full_messages.each do |msg|
        %li= msg
    %input{:name => "utf8", :type => "hidden", :value => "✓"}/
    %input{:name => "authenticity_token", :type => "hidden", :value => "AxFKlYEhD6eqX1PiZoTYQDANtKvgcFSXZQXHt5hyTl55/U/CHC5rtPavrcu2za65riz4tekZEy56vP6kEb2wYA=="}/

app/views/common/_group.html.haml
= form_for @group do |f|
  = render partial: "common/error", locals: { error: @group.errors }
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :グループ名, class: "group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, class: "group-form", placeholder: "グループ名を入力してください"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバーの追加, class: "group-form__label"
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input.group-form{ placeholder: "追加したいユーザー名を入力してください", id: "group-users"}
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー, class: "group-form__label"
    .chat-group-form__field--right
      #chat-group-users
        .chat-group-user.clearfix{ id: "group-user-#{current_user.id}" }
          = current_user.name
          = f.hidden_field "user_ids][", value: current_user.id
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "Save", class: "chat-group-form__action-btn"

app/views/common/_groups.html.haml
.group-link
  = link_to group_messages_path(group) do
    .group-name
      = group.name
    .group-message
      - if group.messages.last
        = group.messages.last.body

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループを編集
  = render partial: "common/group", locals: { group: @group }

app/views/groups/index.html.haml
.chat
  .chat-side
    .chat__user
      %p.chat__user--current
        = current_user.name
      %a.chat-user__action(href="/users/edit")
        %i.fa.fa-cog.icon-cog
      %a.chat-user__action(href="/groups/new")
        %i.fa.fa-edit.icon-edit
    .chat__group-name
      - current_user.groups.each do |group|
        = render partial: "common/groups", locals: { group: group }

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: "common/group", locals: { group: @group }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = bootstrap_flash
    = yield

app/views/messages/_message.html.haml
- group.messages.each do |message|
  .message-written
    .message-user
      =message.user.name
    .message-time
      =message.created_at
    .message-text
      =message.body
    .message-image
      - if message.image.url
        =image_tag message.image.url(:thumb)

app/views/messages/index.html.haml
.chat
  .chat-side
    .chat__user
      %p.chat__user--current
        = current_user.name
      %a.chat-user__action(href="/users/edit")
        %i.fa.fa-cog.icon-cog
      %a.chat-user__action(href="/groups/new")
        %i.fa.fa-edit.icon-edit
    .chat__group-name
      - current_user.groups.each do |group|
        = render partial: "common/groups", locals: { group: group }
  .chat-main
    .chat-header
      .chat-header--left
        = @group.name
        .group-members
          - @group.users.each do |user|
            = user.name
      .chat-header--right
        = link_to edit_group_path(@group), class: "chat-header--right-link" do
          .chat-header__edit-btn Edit
    .chat__message--written
      = render partial: 'message', locals: { group: @group }
    .chat__message--write
      = form_for [@group, @message], class: "message-form" do |f|
        .message-body
          = f.text_field :body, placeholder: "type a message", class: "message-type"
          %label.chat-footer__file
            = f.file_field :image
            %i.fa.fa-photo.icon-photo
        = f.submit "Send", class: "send-button"